name = "query-rs"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-06-28"

[dev]
port = 8080
local_protocol = "http"

[[r2_buckets]]
binding = "QUERY_INDEX"
bucket_name = "query-index"

[[d1_databases]]
binding = "DB"
database_name = "query-rs"
database_id = "7efa9665-3a10-4a55-880b-7fb06e10841e"
